import type {
  Brand,
  Bundle,
  Category,
  Collection,
  Product,
  ProductRelationship,
  ProductSystem,
  AccessoryGroup,
  UseCase,
} from './types'

const egp = (amount: number) => ({ amount, currency: 'EGP' as const })

export const products: Product[] = [
  {
    id: 'p-mirrorless-a',
    slug: 'sonar-a7-iv-body',
    name: 'Aperture A7 IV',
    brand: 'Sonar',
    configuration: 'Body only · 33MP full-frame',
    category: 'cameras',
    price: egp(129900),
    previousPrice: egp(139900),
    rating: 4.8,
    reviewCount: 214,
    stock: 'in_stock',
    image: '/products/mirrorless-a.png',
    badges: ['best_seller', 'sale'],
    useCases: ['photography', 'wedding', 'filmmaking'],
    installmentFrom: 5410,
    official: true,
    branches: ['Downtown', 'Heliopolis'],
  },
  {
    id: 'p-mirrorless-b',
    slug: 'fuji-x-t5-silver',
    name: 'Fujin X-T5',
    brand: 'Fujin',
    configuration: 'Body only · 40MP APS-C',
    category: 'cameras',
    price: egp(94900),
    rating: 4.9,
    reviewCount: 156,
    stock: 'low_stock',
    image: '/products/mirrorless-b.png',
    badges: ['new'],
    useCases: ['photography', 'travel'],
    installmentFrom: 3954,
    official: true,
    branches: ['Downtown'],
  },
  {
    id: 'p-cinema',
    slug: 'blackfin-6k-cinema',
    name: 'Blackfin Pocket 6K',
    brand: 'Blackfin',
    configuration: 'Super 35 · EF mount',
    category: 'video',
    price: egp(112500),
    rating: 4.7,
    reviewCount: 88,
    stock: 'preorder',
    image: '/products/cinema-camera.png',
    badges: ['exclusive'],
    useCases: ['filmmaking', 'studio'],
    installmentFrom: 4687,
    official: true,
    branches: ['Downtown'],
  },
  {
    id: 'p-lens-zoom',
    slug: 'rf-24-70-f28',
    name: 'Aperture RF 24-70mm',
    brand: 'Sonar',
    configuration: 'f/2.8 L · standard zoom',
    category: 'lenses',
    price: egp(89900),
    previousPrice: egp(96000),
    rating: 4.9,
    reviewCount: 132,
    stock: 'in_stock',
    image: '/products/lens-zoom.png',
    badges: ['sale', 'best_seller'],
    useCases: ['wedding', 'photography', 'filmmaking'],
    installmentFrom: 3745,
    official: true,
    branches: ['Downtown', 'Heliopolis'],
  },
  {
    id: 'p-lens-prime',
    slug: 'sigmoid-85-f14',
    name: 'Sigmoid 85mm',
    brand: 'Sigmoid',
    configuration: 'f/1.4 DG DN Art',
    category: 'lenses',
    price: egp(42900),
    rating: 4.8,
    reviewCount: 97,
    stock: 'in_stock',
    image: '/products/lens-prime.png',
    badges: [],
    useCases: ['photography', 'wedding'],
    installmentFrom: 1787,
    official: true,
    branches: ['Heliopolis'],
  },
  {
    id: 'p-drone',
    slug: 'djx-air-3',
    name: 'DJX Air 3',
    brand: 'DJX',
    configuration: 'Dual-cam · 46 min flight',
    category: 'drones',
    price: egp(58500),
    rating: 4.7,
    reviewCount: 176,
    stock: 'in_stock',
    image: '/products/drone.png',
    badges: ['best_seller'],
    useCases: ['travel', 'filmmaking'],
    installmentFrom: 2437,
    official: true,
    branches: ['Downtown', 'Heliopolis'],
  },
  {
    id: 'p-mic',
    slug: 'djx-mic-2',
    name: 'DJX Mic 2',
    brand: 'DJX',
    configuration: 'Wireless · 2 TX + RX',
    category: 'audio',
    price: egp(18900),
    previousPrice: egp(21500),
    rating: 4.8,
    reviewCount: 240,
    stock: 'in_stock',
    image: '/products/wireless-mic.png',
    badges: ['sale', 'best_seller'],
    useCases: ['vlogging', 'streaming', 'podcasting'],
    installmentFrom: 787,
    official: true,
    branches: ['Downtown', 'Heliopolis'],
  },
  {
    id: 'p-gimbal',
    slug: 'djx-rs-4',
    name: 'DJX RS 4',
    brand: 'DJX',
    configuration: '3-axis stabilizer · 3kg',
    category: 'creator-gear',
    price: egp(31900),
    rating: 4.7,
    reviewCount: 64,
    stock: 'low_stock',
    image: '/products/gimbal.png',
    badges: ['new'],
    useCases: ['filmmaking', 'vlogging'],
    installmentFrom: 1329,
    official: true,
    branches: ['Downtown'],
  },
  {
    id: 'p-light',
    slug: 'lumio-120d',
    name: 'Lumio 120d II',
    brand: 'Lumio',
    configuration: 'Daylight COB · Bowens',
    category: 'lighting',
    price: egp(24900),
    rating: 4.6,
    reviewCount: 51,
    stock: 'in_stock',
    image: '/products/led-light.png',
    badges: [],
    useCases: ['studio', 'filmmaking', 'podcasting'],
    installmentFrom: 1037,
    official: true,
    branches: ['Heliopolis'],
  },
  {
    id: 'p-tripod',
    slug: 'peakline-video-tripod',
    name: 'Peakline VT-1',
    brand: 'Peakline',
    configuration: 'Carbon · fluid head',
    category: 'accessories',
    price: egp(14900),
    previousPrice: egp(16900),
    rating: 4.5,
    reviewCount: 38,
    stock: 'in_stock',
    image: '/products/tripod.png',
    badges: ['sale'],
    useCases: ['filmmaking', 'studio', 'travel'],
    installmentFrom: 620,
    official: true,
    branches: ['Downtown', 'Heliopolis'],
  },
  {
    id: 'p-action',
    slug: 'gopeak-13-black',
    name: 'GoPeak 13 Black',
    brand: 'GoPeak',
    configuration: '5.3K60 · waterproof',
    category: 'cameras',
    price: egp(22900),
    rating: 4.6,
    reviewCount: 189,
    stock: 'out_of_stock',
    image: '/products/action-cam.png',
    badges: [],
    useCases: ['travel', 'vlogging'],
    official: true,
    branches: [],
  },
  {
    id: 'p-hero',
    slug: 'aperture-a7r-v-kit',
    name: 'Aperture A7R V',
    brand: 'Sonar',
    configuration: 'with 24-70mm f/2.8',
    category: 'cameras',
    price: egp(184900),
    previousPrice: egp(199000),
    rating: 4.9,
    reviewCount: 76,
    stock: 'in_stock',
    image: '/images/hero-mirrorless.png',
    badges: ['new', 'exclusive'],
    useCases: ['photography', 'studio', 'wedding'],
    installmentFrom: 7704,
    official: true,
    branches: ['Downtown', 'Heliopolis'],
  },
]

export const categories: Category[] = [
  {
    slug: 'cameras',
    name: 'Cameras',
    tagline: 'Mirrorless, cinema, compact & action',
    itemCount: 320,
    columns: [
      {
        heading: 'Shop by type',
        links: [
          { label: 'Mirrorless', href: '/c/cameras/mirrorless' },
          { label: 'Cinema', href: '/c/cameras/cinema' },
          { label: 'Compact', href: '/c/cameras/compact' },
          { label: 'Action', href: '/c/cameras/action' },
          { label: 'Instant', href: '/c/cameras/instant' },
        ],
      },
      {
        heading: 'Shop by brand',
        links: [
          { label: 'Sonar', href: '/b/sonar' },
          { label: 'Canonet', href: '/b/canonet' },
          { label: 'Nikkor', href: '/b/nikkor' },
          { label: 'Fujin', href: '/b/fujin' },
          { label: 'Blackfin', href: '/b/blackfin' },
        ],
      },
      {
        heading: 'Shop by use',
        links: [
          { label: 'Photography', href: '/w/photography' },
          { label: 'Video', href: '/w/filmmaking' },
          { label: 'Vlogging', href: '/w/vlogging' },
          { label: 'Professional cinema', href: '/w/filmmaking' },
        ],
      },
    ],
    featuredProductId: 'p-hero',
  },
  {
    slug: 'lenses',
    name: 'Lenses',
    tagline: 'Primes, zooms & cine glass',
    itemCount: 410,
    columns: [
      {
        heading: 'Shop by type',
        links: [
          { label: 'Prime', href: '/c/lenses/prime' },
          { label: 'Zoom', href: '/c/lenses/zoom' },
          { label: 'Cine', href: '/c/lenses/cine' },
          { label: 'Macro', href: '/c/lenses/macro' },
          { label: 'Telephoto', href: '/c/lenses/telephoto' },
        ],
      },
      {
        heading: 'Shop by mount',
        links: [
          { label: 'Sonar E', href: '/c/lenses/e-mount' },
          { label: 'Canonet RF', href: '/c/lenses/rf-mount' },
          { label: 'Nikkor Z', href: '/c/lenses/z-mount' },
          { label: 'Fujin X', href: '/c/lenses/x-mount' },
          { label: 'L-Mount', href: '/c/lenses/l-mount' },
        ],
      },
      {
        heading: 'Shop by brand',
        links: [
          { label: 'Sigmoid', href: '/b/sigmoid' },
          { label: 'Tamon', href: '/b/tamon' },
          { label: 'Sonar', href: '/b/sonar' },
          { label: 'Canonet', href: '/b/canonet' },
        ],
      },
    ],
    featuredProductId: 'p-lens-zoom',
  },
  {
    slug: 'video',
    name: 'Video',
    tagline: 'Cinema bodies, monitors & rigs',
    itemCount: 180,
    columns: [
      {
        heading: 'Cameras',
        links: [
          { label: 'Cinema cameras', href: '/c/video/cinema' },
          { label: 'Camcorders', href: '/c/video/camcorders' },
          { label: 'Box cameras', href: '/c/video/box' },
        ],
      },
      {
        heading: 'Support & monitoring',
        links: [
          { label: 'Monitors', href: '/c/video/monitors' },
          { label: 'Cages & rigs', href: '/c/video/rigs' },
          { label: 'Follow focus', href: '/c/video/focus' },
          { label: 'Matte boxes', href: '/c/video/matte' },
        ],
      },
      {
        heading: 'Power',
        links: [
          { label: 'V-mount', href: '/c/video/v-mount' },
          { label: 'Batteries', href: '/c/video/batteries' },
        ],
      },
    ],
    featuredProductId: 'p-cinema',
  },
  {
    slug: 'audio',
    name: 'Audio',
    tagline: 'Mics, recorders & monitoring',
    itemCount: 150,
    columns: [
      {
        heading: 'Microphones',
        links: [
          { label: 'Wireless', href: '/c/audio/wireless' },
          { label: 'Shotgun', href: '/c/audio/shotgun' },
          { label: 'Studio / USB', href: '/c/audio/studio' },
          { label: 'Lavalier', href: '/c/audio/lav' },
        ],
      },
      {
        heading: 'Recording',
        links: [
          { label: 'Field recorders', href: '/c/audio/recorders' },
          { label: 'Interfaces', href: '/c/audio/interfaces' },
          { label: 'Headphones', href: '/c/audio/headphones' },
        ],
      },
      {
        heading: 'Shop by brand',
        links: [
          { label: 'Rhode', href: '/b/rhode' },
          { label: 'DJX', href: '/b/djx' },
        ],
      },
    ],
    featuredProductId: 'p-mic',
  },
  {
    slug: 'lighting',
    name: 'Lighting',
    tagline: 'COB, panels & modifiers',
    itemCount: 130,
    columns: [
      {
        heading: 'Lights',
        links: [
          { label: 'COB / point source', href: '/c/lighting/cob' },
          { label: 'Panels', href: '/c/lighting/panels' },
          { label: 'Tube lights', href: '/c/lighting/tubes' },
          { label: 'On-camera', href: '/c/lighting/on-camera' },
        ],
      },
      {
        heading: 'Modifiers',
        links: [
          { label: 'Softboxes', href: '/c/lighting/softboxes' },
          { label: 'Umbrellas', href: '/c/lighting/umbrellas' },
          { label: 'Grids', href: '/c/lighting/grids' },
        ],
      },
      {
        heading: 'Stands',
        links: [
          { label: 'Light stands', href: '/c/lighting/stands' },
          { label: 'C-stands', href: '/c/lighting/c-stands' },
        ],
      },
    ],
    featuredProductId: 'p-light',
  },
  {
    slug: 'drones',
    name: 'Drones',
    tagline: 'Aerial & FPV systems',
    itemCount: 60,
    columns: [
      {
        heading: 'Shop by type',
        links: [
          { label: 'Camera drones', href: '/c/drones/camera' },
          { label: 'FPV', href: '/c/drones/fpv' },
          { label: 'Sub-250g', href: '/c/drones/mini' },
        ],
      },
      {
        heading: 'Accessories',
        links: [
          { label: 'Batteries', href: '/c/drones/batteries' },
          { label: 'ND filters', href: '/c/drones/nd' },
          { label: 'Cases', href: '/c/drones/cases' },
        ],
      },
    ],
    featuredProductId: 'p-drone',
  },
  {
    slug: 'creator-gear',
    name: 'Creator Gear',
    tagline: 'Gimbals, streaming & mobile',
    itemCount: 220,
    columns: [
      {
        heading: 'Stabilization',
        links: [
          { label: 'Gimbals', href: '/c/creator-gear/gimbals' },
          { label: 'Sliders', href: '/c/creator-gear/sliders' },
        ],
      },
      {
        heading: 'Streaming',
        links: [
          { label: 'Capture cards', href: '/c/creator-gear/capture' },
          { label: 'Webcams', href: '/c/creator-gear/webcams' },
          { label: 'Stream decks', href: '/c/creator-gear/decks' },
        ],
      },
      {
        heading: 'Mobile',
        links: [
          { label: 'Phone rigs', href: '/c/creator-gear/phone' },
          { label: 'Ring lights', href: '/c/creator-gear/ring-lights' },
        ],
      },
    ],
    featuredProductId: 'p-gimbal',
  },
  {
    slug: 'accessories',
    name: 'Accessories',
    tagline: 'Support, storage & power',
    itemCount: 540,
    columns: [
      {
        heading: 'Support',
        links: [
          { label: 'Tripods', href: '/c/accessories/tripods' },
          { label: 'Monopods', href: '/c/accessories/monopods' },
          { label: 'Heads', href: '/c/accessories/heads' },
        ],
      },
      {
        heading: 'Storage',
        links: [
          { label: 'Memory cards', href: '/c/accessories/cards' },
          { label: 'SSDs', href: '/c/accessories/ssd' },
          { label: 'Readers', href: '/c/accessories/readers' },
        ],
      },
      {
        heading: 'Carry',
        links: [
          { label: 'Backpacks', href: '/c/accessories/backpacks' },
          { label: 'Hard cases', href: '/c/accessories/cases' },
        ],
      },
    ],
    featuredProductId: 'p-tripod',
  },
]

export const brands: Brand[] = [
  { slug: 'sonar', name: 'Sonar', tagline: 'Full-frame imaging', productCount: 142 },
  { slug: 'canonet', name: 'Canonet', tagline: 'Optics & bodies', productCount: 168 },
  { slug: 'nikkor', name: 'Nikkor', tagline: 'Precision glass', productCount: 121 },
  { slug: 'fujin', name: 'Fujin', tagline: 'Color science', productCount: 89 },
  { slug: 'djx', name: 'DJX', tagline: 'Aerial & motion', productCount: 74 },
  { slug: 'blackfin', name: 'Blackfin', tagline: 'Digital cinema', productCount: 33 },
  { slug: 'sigmoid', name: 'Sigmoid', tagline: 'Art lenses', productCount: 96 },
  { slug: 'tamon', name: 'Tamon', tagline: 'Versatile zooms', productCount: 58 },
  { slug: 'rhode', name: 'Rhode', tagline: 'Location sound', productCount: 64 },
  { slug: 'smallgear', name: 'SmallGear', tagline: 'Rigging & support', productCount: 210 },
]

export const useCases: UseCase[] = [
  {
    slug: 'vlogging',
    name: 'Vlogging',
    description: 'Lightweight kits that keep you sharp, stabilized and clearly heard on the move.',
    image: '/workflow/vlogging.png',
    gear: ['Camera', 'Wide lens', 'Microphone', 'Gimbal', 'Memory'],
    productCount: 86,
  },
  {
    slug: 'podcasting',
    name: 'Podcasting',
    description: 'Broadcast-grade voice with interfaces, monitoring and studio lighting.',
    image: '/workflow/podcast.png',
    gear: ['Microphones', 'Interface', 'Headphones', 'Lighting', 'Stands'],
    productCount: 54,
  },
  {
    slug: 'wedding',
    name: 'Wedding',
    description: 'Fast glass, reliable bodies and lighting built for once-in-a-lifetime moments.',
    image: '/workflow/wedding.png',
    gear: ['Two bodies', 'Fast primes', 'Flash', 'Storage', 'Batteries'],
    productCount: 72,
  },
  {
    slug: 'filmmaking',
    name: 'Filmmaking',
    description: 'Cinema bodies, monitoring, audio and power for a full production rig.',
    image: '/workflow/filmmaking.png',
    gear: ['Cinema camera', 'Cine lens', 'Monitor', 'Audio', 'Rig', 'Power'],
    productCount: 118,
  },
]

export const bundles: Bundle[] = [
  {
    id: 'bundle-vlog',
    slug: 'creator-vlog-kit',
    name: 'Creator Vlog Kit',
    description: 'Everything to shoot, stabilize and record clean audio from day one.',
    useCase: 'vlogging',
    items: [
      { role: 'Camera', productId: 'p-mirrorless-b' },
      { role: 'Microphone', productId: 'p-mic' },
      { role: 'Gimbal', productId: 'p-gimbal' },
    ],
    bundlePrice: egp(139900),
    originalPrice: egp(145700),
    badge: 'Save EGP 5,800',
  },
  {
    id: 'bundle-podcast',
    slug: 'studio-podcast-kit',
    name: 'Studio Podcast Kit',
    description: 'A ready-to-record voice booth with lighting for video podcasts.',
    useCase: 'podcasting',
    items: [
      { role: 'Microphone', productId: 'p-mic' },
      { role: 'Key light', productId: 'p-light' },
      { role: 'Support', productId: 'p-tripod' },
    ],
    bundlePrice: egp(56900),
    originalPrice: egp(58700),
    badge: 'Save EGP 1,800',
  },
  {
    id: 'bundle-film',
    slug: 'indie-film-rig',
    name: 'Indie Film Rig',
    description: 'A compact cinema package with glass, support and lighting.',
    useCase: 'filmmaking',
    items: [
      { role: 'Cinema camera', productId: 'p-cinema' },
      { role: 'Prime lens', productId: 'p-lens-prime' },
      { role: 'Lighting', productId: 'p-light' },
    ],
    bundlePrice: egp(174900),
    originalPrice: egp(180300),
    badge: 'Save EGP 5,400',
  },
]

export const collections: Collection[] = [
  {
    slug: 'trending',
    name: 'Trending this week',
    productIds: ['p-mic', 'p-drone', 'p-mirrorless-a', 'p-lens-zoom', 'p-gimbal', 'p-action'],
  },
  {
    slug: 'new-arrivals',
    name: 'New arrivals',
    productIds: ['p-mirrorless-b', 'p-gimbal', 'p-hero', 'p-cinema'],
  },
  {
    slug: 'deals',
    name: 'Deals worth the shot',
    productIds: ['p-mirrorless-a', 'p-lens-zoom', 'p-mic', 'p-tripod'],
  },
]

export const productSystems: ProductSystem[] = [
  { id: 'system-sonar-e', slug: 'sonar-e', name: 'Sonar E', brandId: 'sonar', categoryIds: ['cameras', 'lenses'] },
  { id: 'system-fujin-x', slug: 'fujin-x', name: 'Fujin X', brandId: 'fujin', categoryIds: ['cameras', 'lenses'] },
  { id: 'system-rf', slug: 'rf-mount', name: 'RF Mount', brandId: 'canonet', categoryIds: ['cameras', 'lenses'] },
]

export const accessoryGroups: AccessoryGroup[] = [
  { id: 'power', slug: 'batteries-power', name: 'Batteries & Power', categoryIds: ['cameras', 'video'] },
  { id: 'storage', slug: 'memory-storage', name: 'Memory & Storage', categoryIds: ['cameras', 'video'] },
  { id: 'support', slug: 'tripods-support', name: 'Tripods & Support', categoryIds: ['cameras', 'video', 'creator-gear'] },
  { id: 'audio', slug: 'microphones', name: 'Microphones', categoryIds: ['cameras', 'video', 'audio'] },
]

export const productRelationships: ProductRelationship[] = [
  { sourceProductId: 'p-mirrorless-a', targetProductId: 'p-lens-zoom', type: 'lens_for', status: 'compatible', priority: 1 },
  { sourceProductId: 'p-mirrorless-a', targetProductId: 'p-lens-prime', type: 'lens_for', status: 'compatible', priority: 2 },
  { sourceProductId: 'p-mirrorless-a', targetProductId: 'p-mic', type: 'microphone_for', status: 'recommended', priority: 3 },
  { sourceProductId: 'p-mirrorless-a', targetProductId: 'p-gimbal', type: 'gimbal_for', status: 'compatible', priority: 4 },
  { sourceProductId: 'p-mirrorless-a', targetProductId: 'p-tripod', type: 'frequently_bought_with', status: 'recommended', priority: 5 },
  { sourceProductId: 'p-cinema', targetProductId: 'p-lens-prime', type: 'lens_for', status: 'compatible', priority: 1 },
  { sourceProductId: 'p-mic', targetProductId: 'p-light', type: 'frequently_bought_with', status: 'recommended', priority: 1 },
]
