import Link from 'next/link'
import { ArrowRight, Check, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { commerce, formatMoney } from '@/lib/commerce'
import { ProductCard } from './product-card'

export function ExperiencePage({ name, description }: { name: string; description: string }) { const products = commerce.products.byUseCase(name.toLowerCase()).slice(0, 6); return <main className="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 sm:py-12"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand">Creator setups</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">{name}</h1><p className="mt-4 max-w-2xl text-muted-foreground">{description}</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{['Choose your camera', 'Choose your audio', 'Add stabilization', 'Add lighting', 'Storage & power'].map((step, index) => <Link href={`/c/${name.toLowerCase() === 'vlogging' ? 'cameras' : 'creator-gear'}`} key={step} className="group rounded-xl border border-border p-4 transition-colors hover:border-brand sm:p-5"><div className="relative mb-4 aspect-[16/9] overflow-hidden rounded-lg bg-muted"><div className="absolute inset-0 flex items-center justify-center text-xs font-semibold uppercase tracking-wider text-muted-foreground">{name} setup</div></div><span className="text-sm font-semibold text-brand">0{index + 1}</span><h2 className="mt-3 text-lg font-semibold group-hover:text-brand">{step}</h2><p className="mt-2 text-sm text-muted-foreground">Shop compatible essentials for your next {name.toLowerCase()} project.</p><ArrowRight className="mt-5 size-4 text-brand" /></Link>)}</div><h2 className="mt-14 text-2xl font-semibold">Recommended for {name}</h2><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{products.length ? products.map((product) => <ProductCard key={product.id} product={product} />) : commerce.products.trending().map((product) => <ProductCard key={product.id} product={product} />)}</div></main> }

export function BundlePage() { const products = commerce.products.trending().slice(0, 3); const total = products.reduce((sum, product) => sum + product.price.amount, 0); return <main className="mx-auto max-w-[1200px] px-4 py-8 sm:px-6 sm:py-12"><div className="grid gap-10 lg:grid-cols-[1fr_0.8fr]"><section><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand">Shams bundle</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">The creator starter setup</h1><p className="mt-4 max-w-xl leading-7 text-muted-foreground">A considered collection of essentials for making your first complete setup. Compatible, practical and backed by our team.</p><div className="mt-8 flex flex-col gap-3">{products.map((product) => <div key={product.id} className="flex items-center gap-4 rounded-lg border border-border p-3"><div className="relative size-16 rounded bg-white"><img src={product.image} alt={product.name} className="size-full object-contain p-1" /></div><div className="flex-1"><p className="font-medium">{product.name}</p><p className="text-sm text-muted-foreground">{formatMoney(product.price)}</p></div><Check className="size-5 text-brand" /></div>)}</div></section><aside className="h-fit rounded-xl border border-border bg-card p-6"><Sparkles className="size-5 text-brand" /><h2 className="mt-5 text-xl font-semibold">Complete bundle</h2><div className="mt-5 flex items-baseline gap-3"><span className="text-3xl font-semibold">{formatMoney({ amount: Math.round(total * 0.94), currency: 'EGP' })}</span><del className="text-sm text-muted-foreground">{formatMoney({ amount: total, currency: 'EGP' })}</del></div><p className="mt-2 text-sm text-brand">Save 6% when bought together</p><Button className="mt-6 min-h-12 w-full">Add entire bundle</Button><Link href="/" className="mt-4 block text-center text-sm text-muted-foreground">Continue shopping</Link></aside></div></main> }
