'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useRef, useState } from 'react'
import { useInteractions } from '@/components/shams/providers'
import { ArrowRight, Check, Package, Plus, ShieldCheck, ShoppingCart } from 'lucide-react'
import type { BundleDetail } from '@/lib/commerce'
import { commerce, formatEgp, formatMoney } from '@/lib/commerce'
import { AddBundleButton } from './add-bundle-button'

export function BundleDetailPage({ bundle }: { bundle: BundleDetail }) {
  const [showStickyPurchase, setShowStickyPurchase] = useState(false)
  const purchaseRef = useRef<HTMLDivElement>(null)
  const { setStickyPurchaseVisible } = useInteractions()
  useEffect(() => {
    const element = purchaseRef.current
    if (!element) return
    const observer = new IntersectionObserver(([entry]) => { const visible = !entry.isIntersecting; setShowStickyPurchase(visible); setStickyPurchaseVisible(visible) }, { threshold: 0.1 })
    observer.observe(element)
    return () => { observer.disconnect(); setStickyPurchaseVisible(false) }
  }, [setStickyPurchaseVisible])
  const savings = bundle.originalPrice.amount - bundle.bundlePrice.amount
  const useCase = commerce.useCases.bySlug(bundle.useCase)
  const availability = bundle.availability === 'available' ? 'All required items are ready to ship' : bundle.availability === 'low_stock' ? 'One or more items are moving quickly' : bundle.availability === 'partially_available' ? 'Some required items need attention' : 'This setup is currently unavailable'

  return <main className="mobile-storefront-page pb-[calc(5rem+env(safe-area-inset-bottom))] md:pb-16">
    <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-[1440px] gap-8 px-4 py-8 sm:px-6 sm:py-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-16">
      <div className="relative aspect-[4/3] overflow-hidden rounded-(--radius-editorial) bg-surface-raised p-6 sm:p-10"><div className="flex h-full items-center justify-center gap-2">{bundle.products.slice(0, 3).map((product) => <div key={product.id} className="relative h-48 flex-1 sm:h-64"><Image src={product.image || '/placeholder.svg'} alt={product.name} fill sizes="260px" className="object-contain p-2" /></div>)}</div><span className="absolute left-4 top-4 rounded-full bg-brand px-3 py-1 text-xs font-semibold text-brand-foreground">Complete setup</span></div>
      <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-ink">{useCase?.name} / curated kit</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">{bundle.name}</h1><p className="mt-4 max-w-xl text-base leading-7 text-muted-foreground">{bundle.description}</p><p className="mt-5 text-sm font-medium text-muted-foreground">{availability}</p><div className="mt-6 flex flex-wrap items-end gap-x-5 gap-y-2"><div><p className="text-xs text-muted-foreground">Bundle price</p><p className="text-3xl font-semibold">{formatMoney(bundle.bundlePrice)}</p></div><div><p className="text-sm text-muted-foreground line-through">{formatMoney(bundle.originalPrice)}</p><p className="text-sm font-semibold text-success">Save {formatEgp(savings)}</p></div></div></div>
    </div></section>

    <section className="mx-auto max-w-[1440px] px-4 py-10 sm:px-6 sm:py-14"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-ink">Why this setup works</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Everything has a job.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{useCase?.gear.slice(0, 4).join('. ')}. A focused combination for getting from setup to shooting without missing the essentials.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-(--radius-card) border border-border p-4"><ShieldCheck className="text-brand-ink" /><p className="mt-4 font-semibold">Matched together</p><p className="mt-1 text-sm text-muted-foreground">Core gear chosen for this use case.</p></div><div className="rounded-(--radius-card) border border-border p-4"><Package className="text-brand-ink" /><p className="mt-4 font-semibold">One complete order</p><p className="mt-1 text-sm text-muted-foreground">Add the required pieces in one action.</p></div><div className="rounded-(--radius-card) border border-border p-4"><ShoppingCart className="text-brand-ink" /><p className="mt-4 font-semibold">Clear savings</p><p className="mt-1 text-sm text-muted-foreground">See the individual total before you buy.</p></div></div></section>

    <section className="bg-card"><div className="mx-auto max-w-[1440px] px-4 py-10 sm:px-6 sm:py-14"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-ink">Included products</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">What&apos;s included</h2></div><span className="text-sm text-muted-foreground">{bundle.products.length} items</span></div><div className="mt-7 grid gap-4 lg:grid-cols-3">{bundle.items.map((item, index) => { const product = bundle.products.find((candidate) => candidate.id === item.productId); if (!product) return null; return <article key={item.productId} className="rounded-(--radius-card) border border-border bg-background p-4"><div className="relative aspect-[4/3] rounded-(--radius-control) bg-surface-raised"><Image src={product.image || '/placeholder.svg'} alt={product.name} fill sizes="360px" className="object-contain p-5" /></div><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-brand-ink">{item.role}</span><span className="text-xs text-muted-foreground">{item.required === false ? 'Optional' : 'Required'}</span></div><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{product.brand}</p><h3 className="mt-1 font-semibold">{product.name}</h3><p className="mt-1 text-sm text-muted-foreground">{product.configuration}</p><div className="mt-4 flex items-center justify-between gap-3"><span className="font-semibold">{formatMoney(product.price)}</span><Link href={`/p/${product.slug}`} className="inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-brand-ink">View product <ArrowRight className="size-4" /></Link></div></article> })}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-4 py-10 sm:px-6 sm:py-14"><div className="grid gap-8 lg:grid-cols-[1fr_380px] lg:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-ink">Composition</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">From separate pieces to one setup.</h2><div className="mt-6 flex flex-col items-center gap-3 sm:flex-row">{bundle.products.map((product, index) => <div key={product.id} className="flex w-full items-center gap-3 sm:flex-1"><div className="flex min-h-16 flex-1 items-center gap-3 rounded-(--radius-card) border border-border p-3"><div className="relative size-12 shrink-0"><Image src={product.image || '/placeholder.svg'} alt="" fill sizes="48px" className="object-contain" /></div><span className="line-clamp-2 text-sm font-medium">{product.name}</span></div>{index < bundle.products.length - 1 && <Plus className="hidden size-5 shrink-0 text-muted-foreground sm:block" />}</div>)}<div className="hidden text-xl font-semibold text-brand sm:block">=</div><div className="w-full rounded-(--radius-control) bg-brand p-4 text-center text-sm font-semibold text-brand-foreground sm:w-auto">Complete setup</div></div></div><aside ref={purchaseRef} className="rounded-(--radius-card) border border-border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Purchase summary</p><div className="mt-5 flex justify-between text-sm"><span>Individual total</span><span>{formatMoney(bundle.originalPrice)}</span></div><div className="mt-3 flex justify-between text-sm text-success"><span>Bundle savings</span><span>-{formatMoney({ amount: savings, currency: 'EGP' })}</span></div><div className="mt-4 flex justify-between border-t border-border pt-4 text-lg font-semibold"><span>Bundle price</span><span>{formatMoney(bundle.bundlePrice)}</span></div><AddBundleButton bundleName={bundle.name} bundle={bundle} className="mt-5 w-full" /></aside></div></section>

    <div aria-hidden={!showStickyPurchase} style={{ bottom: showStickyPurchase ? 'calc(var(--fixed-stack-bottom) + var(--compare-tray-offset))' : 'var(--fixed-stack-bottom)' }} className={`pointer-events-none fixed inset-x-0 z-[65] border-t border-border bg-background/95 px-4 pt-3 backdrop-blur transition-[opacity,transform] duration-standard md:hidden ${showStickyPurchase ? 'pointer-events-auto translate-y-0 opacity-100' : 'translate-y-2 opacity-0'} pb-[calc(0.75rem+var(--safe-area-bottom))]`}><div className="mx-auto flex max-w-md items-center gap-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{formatMoney(bundle.bundlePrice)}</p><p className="text-xs font-semibold text-success">Save {formatEgp(savings)}</p></div><AddBundleButton bundleName={bundle.name} bundle={bundle} className="shrink-0" /></div></div>
  </main>
}
